name: docs
channels:
  - defaults
  - conda-forge

dependencies:
    # Base depends
  - python=3.6.15
    # Pip-only installs
  - pip
  - pip:
    - -r requirements.txt
    - pysqlite3
    - sphinx-autoapi
    - pytraj

