name: docs
channels:
  - defaults
  - conda-forge

dependencies:
    # Base depends
  - python
  - pip
  - argparse
  - numpy
  - pandas
  - scipy
  - sqlalchemy
  - networkx

    # Pip-only installs
  - pip:
    - scikit-misc
    - pytraj

