name: docs
channels:
  - conda-forge

dependencies:
    # Base depends
  - python
  - pip
  - argparse
  - numpy
  - pandas
  - scipy
  - sqlalchemy
  - networkx
  - sqlite3

    # Pip-only installs
  #- pip:

