name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip
  - argparse
  - numpy
  - pandas
  - Amber-MD
  - Amber-MD/pytraj
  - pytraj
  - scipy
  - sqlalchemy
  - networkx


    # Pip-only installs
  #- pip:

