name: docs
channels:
  - defaults
  - conda-forge

dependencies:
    # Base depends
  - python
  - argparse
  - numpy
  - pandas
  - scipy
  - sqlalchemy
  - networkx

    # Pip-only installs
#  - pip
#  - pip:
#    - scikit-misc
#    - pytraj

